{{- if .Values.services.core.registry.enabled }}
{{- $serviceValues := .Values.services.core.registry }}
{{- $globalValues := .Values.global }}
{{- $imgName := printf "%s/%s:%s" (include "spacefx.servicePrefixCalc" (dict "globalValues" $globalValues)) $serviceValues.repository (include "spacefx.serviceVersionCalc" (dict "globalValues" $globalValues "serviceValues" $serviceValues)) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceValues.appName | quote }}
  namespace: {{ $serviceValues.serviceNamespace }}
spec:
  type: NodePort
  ports:
    - name: core-registry
      port: {{ $serviceValues.targetPort }}
      targetPort: {{ $serviceValues.targetPort }}
  selector:
    app: {{ $serviceValues.appName | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceValues.appName | quote }}
  namespace: {{ $serviceValues.serviceNamespace | quote }}
  labels:
    app: {{ $serviceValues.appName | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceValues.appName | quote }}
  template:
    metadata:
      labels:
        app: {{ $serviceValues.appName | quote }}
    spec:
      containers:
      - name: {{ $serviceValues.appName | quote }}
        ports:
        - containerPort: {{ $serviceValues.targetPort }}
        image: {{ $imgName | quote }}
        imagePullPolicy: Never
        {{- include "spacefx.resourceLimits" (dict "globalValues" $globalValues "serviceValues" $serviceValues) | indent 8  }}
        command:
        {{- range $serviceValues.containerCommand }}
          - {{ . }}
        {{- end }}
        args:
        {{- range $serviceValues.containerArgs }}
          - {{ . }}
        {{- end }}
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: {{ $serviceValues.tlsCertificate }}
        - name: REGISTRY_HTTP_TLS_KEY
          value: {{ $serviceValues.tlsKey }}
        volumeMounts:
        - name: registry-data-mount
          mountPath: /var/lib/registry
        - name: registry-cert-mount
          mountPath: /certs
      volumes:
      - name: registry-data-mount
        hostPath:
          path: {{ $globalValues.spacefxDirectories.base }}/registry/data
          type: DirectoryOrCreate
      - name: registry-cert-mount
        hostPath:
          path: {{ $globalValues.spacefxDirectories.base }}/certs/registry
          type: DirectoryOrCreate
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
# core-registry generation end
{{- end }}