config:
  channel: stable
  buildArtifacts:
  extraBuildArtifacts:
  extraContainers:
    - repository: spacesdk-base
      tag: 0.11.0
      appendChannel: true
    - repository: spacesdk-base-python
      tag: 0.11.0_3.10
      appendChannel: true
    - repository: python-base
      tag: 3.10
      appendChannel: true
  clusterDataDir: /var/lib/rancher
  charts:
    - group: dapr
      enabled: true
      version: 1.9.6
      namespace: dapr-system
      containers:
        - registry: ghcr.io
          repository: dapr/dapr
          tag: 1.9.6
        - registry: ghcr.io
          repository: dapr/daprd
          tag: 1.9.6
    - group: smb
      enabled: false
      version: 1.15.0
      containers:
        - registry: registry.k8s.io
          repository: sig-storage/livenessprobe
          tag: v2.13.1
        - registry: registry.k8s.io
          repository: sig-storage/csi-node-driver-registrar
          tag: v2.11.1
        - registry: registry.k8s.io
          repository: sig-storage/smbplugin
          tag: v1.15.0
        - registry: registry.k8s.io
          repository: sig-storage/csi-provisioner
          tag: v5.0.1
    - group: buildservice
      enabled: true
      version: 1.20.1
      containers:
        - registry: gcr.io
          repository: kaniko-project/executor
          tag: v1.20.1-slim
    - group: nvidia_gpu
      enabled: false
      version: 0.14.4
      containers:
        - registry: nvcr.io
          repository: nvidia/k8s-device-plugin
          tag: v0.14.4
  containerRegistries:
    - url: ghcr.io
      repositoryPrefix: microsoft/azure-orbital-space-sdk
      push_enabled: true
      pull_enabled: true
      login_enabled: true
      login_username_file: ${HOME}/.ssh/ghcr_username
      login_password_file: ${HOME}/.ssh/ghcr_password
  hostDirectoryMounts:
