name: test setup

on:
    workflow_dispatch:
      inputs:
          VER_DOCKER_MAX:
            description: 'Docker version to install'
            required: false
            type: string
            default: "26.1.3"

    push:
        branches:
        - main


env:
  REGISTRY: ghcr.io
  FEATURE: microsoft/azure-orbital-space-sdk/spacefx-dev

jobs:

  test-setup-amd64:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/run-setup-tests.yaml
    with:
      WORKFLOW_AGENT: ubuntu-latest
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}
  
  test-setup-arm64:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/run-setup-tests.yaml
    with:
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}




